port: 8007
log_level: warning
log_path: "/opt/dimkush_guestbook/log"
audit_level: info

database:
  host: localhost
  port: 5505
  username: postgres
  dbname: postgres
  timezone: Europe/Moscow
  sslmode: disable
