main:
    port: 5002
    log_level: debug
    log_path: /opt/dimkush_guestbook/log/

audit:
    port: 5003
    audit_level: debug
    log_level: error

database:
    db_core: postgres
    db_user: postgres
    db_password: postgres
    db_name: test
    db_port: 5432
    db_connections_pool: 10
